In [1]:
import numpy as np
import tensorflow as tf
from nn_model import NeuralNetworkModel
from nn_agent import NeuralNetworkAgent
from game import TicTacToe

In [2]:
sess = tf.InteractiveSession()

In [3]:
env = TicTacToe()

In [4]:
nn_model = NeuralNetworkModel(sess,
                              '',
                              '',
                              '/Users/adam/Documents/projects/td_learning/tic_tac_toe/checkpoints/', 
                              restore=True)

nn_agent = NeuralNetworkAgent(nn_model)

INFO:tensorflow:Summary name layer_1/W_1:0 is illegal; using layer_1/W_1_0 instead.
INFO:tensorflow:Summary name layer_1/W_1:0/trace_sums is illegal; using layer_1/W_1_0/trace_sums instead.
INFO:tensorflow:Summary name layer_1/b_1:0 is illegal; using layer_1/b_1_0 instead.
INFO:tensorflow:Summary name layer_1/b_1:0/trace_sums is illegal; using layer_1/b_1_0/trace_sums instead.
INFO:tensorflow:Summary name layer_2/W_2:0 is illegal; using layer_2/W_2_0 instead.
INFO:tensorflow:Summary name layer_2/W_2:0/trace_sums is illegal; using layer_2/W_2_0/trace_sums instead.
INFO:tensorflow:Summary name layer_2/b_2:0 is illegal; using layer_2/b_2_0 instead.
INFO:tensorflow:Summary name layer_2/b_2:0/trace_sums is illegal; using layer_2/b_2_0/trace_sums instead.
Restoring checkpoint: /Users/adam/Documents/projects/td_learning/tic_tac_toe/checkpoints/checkpoint.ckpt


In [5]:
nn_model.clone()

TypeError: can't pickle _thread.lock objects

In [7]:
%%timeit
NeuralNetworkAgent(nn_model)

The slowest run took 5.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 541 ns per loop


In [42]:
env.reset()

In [8]:
env.play([nn_agent,nn_agent], verbose=True)

  | | 
-------
  | | 
-------
  | | 

  | | 
-------
  | | 
-------
  | |X

  | | 
-------
  | |O
-------
  | |X

 X| | 
-------
  | |O
-------
  | |X

 X| | 
-------
  | |O
-------
 O| |X

 X| | 
-------
  | |O
-------
 O|X|X

 X|O| 
-------
  | |O
-------
 O|X|X

 X|O| 
-------
 X| |O
-------
 O|X|X

 X|O|O
-------
 X| |O
-------
 O|X|X

 X|O|O
-------
 X|X|O
-------
 O|X|X

X won!


1

In [13]:
legal_moves = env.get_legal_moves()
candidate_boards = nn_model.get_candidate_boards(env)
turns = float(env.turn) * np.ones((len(candidate_boards), 1))
js = nn_model.J.eval(feed_dict={nn_model.boards_placeholder: candidate_boards, 
                                nn_model.turn_placeholder: turns})
for idx, (j, board) in enumerate(zip(js, candidate_boards)):
    print(idx, j)
    env._print(board)
    print(100*'*')

0 [ 0.26372266]
 X| | 
-------
  | | 
-------
  | | 

****************************************************************************************************
1 [ 0.1813571]
  |X| 
-------
  | | 
-------
  | | 

****************************************************************************************************
2 [ 0.20619656]
  | |X
-------
  | | 
-------
  | | 

****************************************************************************************************
3 [ 0.14264873]
  | | 
-------
 X| | 
-------
  | | 

****************************************************************************************************
4 [ 0.17504549]
  | | 
-------
  |X| 
-------
  | | 

****************************************************************************************************
5 [ 0.13307941]
  | | 
-------
  | |X
-------
  | | 

****************************************************************************************************
6 [ 0.10693135]
  | | 
-------
  | | 
-------
 X| | 

*****************

In [14]:
env.make_move(1)

In [27]:
env._print()

  | | 
-------
  | | 
-------
  | | 



In [46]:
move = nn_agent.get_move(env)
env.make_move(move)
env._print()

 X| | 
-------
  | |O
-------
 O| |X



In [47]:
env.board

array([[[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  1.]],

       [[ 0.,  0.,  1.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.]],

       [[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.]]])

In [48]:
env.get_legal_moves()

array([1, 2, 3, 4, 7])

In [58]:
env._print()

 X| | 
-------
  | |O
-------
 O| |X



In [59]:
np.where(env.board[:, :, 2].flatten() == 1)

(array([1, 2, 3, 4, 7]),)

In [56]:
np.array(range(5))[np.where(np.array(range(5))>2)]

array([3, 4])

In [60]:
import random

In [61]:
random.choice(range(5))

3